name: Sync Property Assets

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 1 * *' # Automatically runs once a month on the 1st

jobs:
  sync-assets:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Run Lunch Money Sync Tool
        uses: docker://ghcr.io/iloveitaly/lunchmoney-assets:latest
        env:
          LUNCHMONEY_TOKEN: ${{ secrets.LUNCHMONEY_TOKEN }}
